### ISSUE TITLE
Ignore .classpath and .project

### ISSUE THREAD

**Issue by e9t** [BRoftWook/dmCrawl#1]
Eclipse의 환경설정에 사용되는 .classpath, .project 파일은 커밋하지 않는 것이 일반적입니다.
두 파일을 삭제하고 .gitignore 파일에 두 파일을 추가하는 것이 좋을 것 같네요.

- 참고: http://stackoverflow.com/questions/18955149/ignore-classpath-and-project-from-git

**Comment by BRoftWook** [comment]
두 파일 삭제하고, gitignore파일 추가해서 해결했습니다
